### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Phantom-KNA** [LordOfDragons/dmotools#1]
what happens is that it does not run, in the console it does not give an error, it only closes, is there something I am missing?

**Comment by LordOfDragons** [comment]
Can you post the error you receive?

**Comment by Phantom-KNA** [comment]
Any error my friend only try to open and closed.

**Comment by LordOfDragons** [comment]
That's not much to get started with. When you run it from the console without any arguments it should show you the possible command lines you can use. Since this is a console only application you have to open a console (PowerShell for example) and run it from there. Otherwise the console will close immediately and you see nothing.

**Comment by Phantom-KNA** [comment]
Thanks, I'll try and tell you.

**Comment by Phantom-KNA** [comment]
Thanks, I'll try and tell you.
